name: SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # 1. Check out code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required for Sonar to get full SCM history

      # 2. Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      # 3. (Optional) Verify Java version
      - name: Verify Java version
        run: java -version

      # 4. Cache SonarQube packages
      - name: Cache SonarQube packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 5. Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 6. Run tests to generate coverage data
      - name: Run tests
        working-directory: user-management  # Navigate to the directory with pom.xml
        run: mvn clean test jacoco:report -Dmaven.test.failure.ignore=true

      # 7. Build and analyze with Sonar
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        working-directory: user-management  # Navigate to the directory with pom.xml
        run: |
          mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=JohariOrg_Fitness-Management-System \
            -Dsonar.coverage.exclusions=**/main.java \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
